2023-12-08 16:31:44,187 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:32:44,404 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:33:44,614 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:34:44,792 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:35:44,960 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:36:45,272 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:37:45,458 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:38:45,669 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:39:45,961 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:40:46,066 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:41:46,489 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:42:46,651 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:43:46,868 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:44:47,053 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:45:47,276 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

2023-12-08 16:46:47,494 ERROR scheduler Exception in Enqueue Events for Site yusf
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_618b8a47ffa99eaf.tabSingles' doesn't exist")

